-- Limpar dados existentes da trilha Renovação e recriar com conteúdo completo
DELETE FROM track_daily_activities WHERE daily_content_id IN (
  SELECT id FROM track_daily_content WHERE track_slug = 'renovacao'
);
DELETE FROM track_daily_content WHERE track_slug = 'renovacao';

-- Inserir conteúdo completo da trilha Renovação (40 dias)
-- Dia 1: RENDIÇÃO TOTAL
INSERT INTO track_daily_content (
  track_slug, day_number, title, objective, 
  main_activity_title, main_activity_content,
  main_challenge_title, main_challenge_content,
  devotional_verse, devotional_reflection, devotional_prayer,
  bonus_activity_title, bonus_activity_content,
  difficulty_level, max_points
) VALUES (
  'renovacao', 1, 'RENDIÇÃO TOTAL', 'Admitir completa impotência e entregar-se ao processo',
  'Inventário Completo de Destruição', 
  'Parte 1: A Verdade Nua e Crua (20 min) - Responda com TOTAL honestidade sobre horas de tela, vezes que pegou o celular, compromissos perdidos. Parte 2: Carta de Rendição (20 min) - Escreva carta para o celular admitindo o domínio. Parte 3: Ritual de Entrega (20 min) - Entrega física, simbólica e pública do celular.',
  'Primeiro Dia no Deserto',
  'Regras das Primeiras 24h: Celular fica com outra pessoa, apenas 1 ligação de 5 min supervisionada, sem TV/computador/tablet, apenas Bíblia física, diário e livros.',
  'Miserável homem que eu sou! Quem me livrará do corpo desta morte? - Romanos 7:24',
  'Paulo admitiu sua miséria. Você está no fundo do poço digital. Seu celular se tornou seu deus. Só quando reconhecemos nossa impotência é que o poder de Deus age.',
  'Deus, eu não consigo mais. Estou vencido. Sou escravo. Preciso de Ti. Toma o controle completo. Eu me rendo. Salva-me de mim mesmo. Amém.',
  'Kit Sobrevivência Dia 1',
  'Prepare: 3 refeições, 5 atividades de 30 min, lista de pessoas para visitar, roupa de exercício, livros, diário, versículos na parede.',
  5, 200
);

-- Dia 2: ENFRENTANDO A ABSTINÊNCIA
INSERT INTO track_daily_content (
  track_slug, day_number, title, objective,
  main_activity_title, main_activity_content,
  main_challenge_title, main_challenge_content,
  devotional_verse, devotional_reflection, devotional_prayer,
  bonus_activity_title, bonus_activity_content,
  difficulty_level, max_points
) VALUES (
  'renovacao', 2, 'ENFRENTANDO A ABSTINÊNCIA', 'Sobreviver aos sintomas físicos e mentais',
  'Protocolo de Gerenciamento de Crise',
  'Parte 1: Monitoramento de Sintomas - Registre a cada 2 horas sintomas como ansiedade, irritabilidade. Parte 2: Técnicas de Sobrevivência - Técnica 5-4-3-2-1, respiração 4-4-4-4, âncoras físicas. Parte 3: Protocolo S.O.S - Stop, Observe, Support.',
  'Sobrevivência Minuto a Minuto',
  'Método dos Micro-Compromissos: Resista 5 minutos de cada vez, celebre cada hora vencida. Meta: 16 horas acordado sem ceder.',
  'A minha graça te basta, pois o meu poder se aperfeiçoa na fraqueza - 2 Coríntios 12:9',
  'Hoje seu corpo gritará. É abstinência digital - prova da dependência. Mas Deus promete: Sua graça é suficiente. Na sua fraqueza, Ele é forte.',
  'Senhor, meu corpo está em guerra. Mas escolho depender de Ti. Seja minha força. Passa comigo por este vale. Amém.',
  'Diário de Guerra',
  'Registre: hora de acordar, pior momento, como sobrevivi, batalhas vencidas/perdidas, sintoma mais forte, o que funcionou.',
  5, 200
);

-- Dia 3: QUEBRANDO IDENTIFICAÇÃO
INSERT INTO track_daily_content (
  track_slug, day_number, title, objective,
  main_activity_title, main_activity_content,
  main_challenge_title, main_challenge_content,
  devotional_verse, devotional_reflection, devotional_prayer,
  bonus_activity_title, bonus_activity_content,
  difficulty_level, max_points
) VALUES (
  'renovacao', 3, 'QUEBRANDO IDENTIFICAÇÃO', 'Separar sua identidade da dependência',
  'Reconstrução de Identidade',
  'Parte 1: Desprogramação Mental - Reescreva mentiras em verdades. Parte 2: Arqueologia do Eu Real - Quem você era antes, quem Deus diz que você é. Parte 3: Manifesto de Nova Identidade - Declare quem você é em Cristo.',
  'Prática de Afirmação',
  'Sempre que pensar "eu sou viciado", corrija: "EU ESTOU EM RECUPERAÇÃO". Faça isso 50 vezes hoje.',
  'Já estou crucificado com Cristo; e vivo, não mais eu, mas Cristo vive em mim - Gálatas 2:20',
  'Você não É viciado. Você ESTÁ com comportamento viciante. Sua identidade está em Cristo, não no celular.',
  'Senhor, ajuda-me a ver quem realmente sou em Ti. Quebra as mentiras. Mostra minha verdadeira identidade. Amém.',
  'Espelho da Verdade',
  'Coloque post-its no espelho: "Sou filho de Deus", "Sou mais que vencedor", "Sou nova criatura".',
  5, 200
);

-- Dias 4-10: Continuação da fase QUEBRANTAMENTO
INSERT INTO track_daily_content (track_slug, day_number, title, objective, main_activity_title, main_activity_content, main_challenge_title, main_challenge_content, devotional_verse, devotional_reflection, devotional_prayer, bonus_activity_title, bonus_activity_content, difficulty_level, max_points) VALUES
('renovacao', 4, 'CONFRONTANDO DEMÔNIOS', 'Enfrentar gatilhos e padrões destrutivos', 'Mapeamento de Gatilhos', 'Identifique seus gatilhos: lugares, pessoas, horários, emoções que levam ao uso compulsivo. Crie estratégias específicas para cada gatilho.', 'Dia Sem Gatilhos', 'Evite todos os gatilhos identificados por 24h completas. Crie rotas alternativas, atividades substitutivas.', 'Resisti ao diabo, e ele fugiu de mim - Tiago 4:7', 'Os demônios digitais têm gatilhos específicos. Identificá-los é metade da vitória. Quando você resiste, eles fogem.', 'Senhor, revela meus gatilhos. Da-me força para resistir. Que eu fuja da tentação. Amém.', 'Mapa de Fuga', 'Desenhe mapa da casa/trabalho marcando "zonas de perigo" e "rotas de fuga" dos gatilhos.', 5, 200),
('renovacao', 5, 'LIMPEZA PROFUNDA', 'Eliminar todas as tentações do ambiente', 'Operação Limpeza', 'Delete apps, desinstale jogos, cancele assinaturas, limpe histórico, remove bookmarks tentadores. Limpeza física e digital completa.', 'Casa Limpa', 'Mantenha ambientes 100% livres de tentação digital por 24h. Substitua por livros, plantas, instrumentos.', 'Se teu olho direito te faz tropeçar, arranca-o - Mateus 5:29', 'Jesus foi radical com tentações. Seja radical também. Melhor viver com menos recursos que viver escravo.', 'Senhor, da-me coragem para ser radical. Que eu corte tudo que me afasta de Ti. Amém.', 'Inventário de Limpeza', 'Liste tudo removido: apps (___), jogos (___), assinaturas (___), favoritos (___). Celebre cada exclusão.', 5, 200),
('renovacao', 6, 'CONSTRUINDO MUROS', 'Criar barreiras físicas e mentais', 'Sistema de Barreiras', 'Instale bloqueadores, crie senhas complexas para recuperação, configure horários de uso, estabeleça accountability partner.', 'Teste das Barreiras', 'Tente deliberadamente burlar suas próprias barreiras. Identifique pontos fracos e reforce.', 'Sobre todo o cuidado, guarda o teu coração - Provérbios 4:23', 'Seu coração precisa de muros de proteção. Não confie na força de vontade apenas - crie sistemas.', 'Senhor, ajuda-me a construir muros sábios. Protege meu coração das tentações. Amém.', 'Mapa de Fortificação', 'Desenhe suas defesas: barreiras físicas, digitais, sociais, espirituais. Onde precisa reforçar?', 4, 180),
('renovacao', 7, 'SEMANA DE GUERRA', 'Celebrar primeira semana de batalha', 'Relatório de Guerra', 'Analise: vitórias, derrotas, aprendizados, mudanças físicas/mentais, reações da família, desafios superados.', 'Dia do Guerreiro', 'Aja como guerreiro vitorioso: postura ereta, decisões firmes, palavras de poder, autoridade espiritual.', 'O Senhor é homem de guerra - Êxodo 15:3', '7 dias de guerra! Você provou que é guerreiro. Deus é seu general. Continue lutando com Ele.', 'Senhor, obrigado por me sustentar 7 dias. Continue sendo meu general nesta guerra. Amém.', 'Medalha de 7 Dias', 'Crie medalha simbólica: "Guerreiro de 7 dias - Primeira vitória conquistada!"', 4, 250),
('renovacao', 8, 'VALLE DA DECISÃO', 'Momento crucial de escolha definitiva', 'Hora da Verdade', 'Decisão final: continuar até o fim ou desistir. Escreva carta de compromisso. Assine com testemunhas.', 'Juramento Público', 'Declare publicamente (família/amigos): "Vou completar os 40 dias. Me cobrem se eu fraquejar."', 'Escolhei hoje a quem sirvais - Josué 24:15', 'Momento de escolha definitiva. Não há meio termo. Você serve a Deus ou aos dispositivos. Escolha hoje.', 'Senhor, escolho Te servir. Renovo meu compromisso. Sustenta-me até o fim. Amém.', 'Contrato Sagrado', 'Escreva contrato formal consigo mesmo e com Deus. Assine, date, cole no espelho.', 5, 200),
('renovacao', 9, 'MORTE DO EU', 'Morrer para os desejos da carne', 'Ritual de Morte', 'Cerimônia simbólica: escreva lista de comportamentos antigos, queime, enterre as cinzas. Declare: "Morreu o velho eu".', 'Jejum Digital', 'Jejum completo de telas (exceto trabalho essencial supervisionado). Substitua por jejum de oração.', 'Morri para o pecado; como viveremos ainda nele? - Romanos 6:2', 'Para nascer de novo, o velho deve morrer. Hoje você morre para a escravidão digital. É funeral necessário.', 'Senhor, que morra em mim tudo que não vem de Ti. Sepulta meus vícios. Ressuscita nova vida. Amém.', 'Certidão de Óbito', 'Preencha certidão simbólica do "velho eu": nome, vícios, data da "morte", causa: "Encontrou Cristo".', 5, 200),
('renovacao', 10, 'MARCO DE RESISTÊNCIA', 'Celebrar 10 dias e preparar próxima fase', 'Checkpoint de Transformação', 'Compare Dia 1 vs Dia 10 em todas as áreas. Escreva testemunho para futuros guerreiros. Prepare-se para Fase 2.', 'Celebração Sóbria', 'Comemore com: jantar especial, carta aos apoiadores, presente simbólico, renovação de compromissos.', 'Aquele que perseverar até o fim será salvo - Mateus 24:13', '10 dias! Você sobreviveu ao inferno. Os próximos 30 dias solidificarão sua transformação total.', 'Senhor, obrigado por me sustentar 10 dias. Continue me fortalecendo pelos próximos 30. Amém.', 'Medalha de Honra', 'Crie certificado: "10 DIAS DE GUERRA VENCIDOS - Sobreviveu ao inferno, enfrentou demônios, escolheu liberdade"', 4, 300);

-- Dias 11-20: Fase RECONSTRUÇÃO
INSERT INTO track_daily_content (track_slug, day_number, title, objective, main_activity_title, main_activity_content, main_challenge_title, main_challenge_content, devotional_verse, devotional_reflection, devotional_prayer, bonus_activity_title, bonus_activity_content, difficulty_level, max_points) VALUES
('renovacao', 11, 'NOVA FUNDAÇÃO', 'Estabelecer base sólida para nova vida', 'Pilares da Nova Vida', 'Defina 7 pilares: Espiritual, Físico, Mental, Emocional, Social, Profissional, Recreativo. Crie plano de ação para cada.', 'Dia dos Pilares', 'Toque todos os 7 pilares hoje: oração, exercício, aprendizado, journaling, conversa profunda, trabalho focado, hobbie.', 'Ninguém pode pôr outro fundamento além do que está posto: Jesus Cristo - 1 Coríntios 3:11', 'A casa velha foi demolida. Agora construímos sobre nova fundação. Cristo é a rocha sólida.', 'Senhor, seja Tu a fundação da minha nova vida. Que tudo seja construído sobre Ti. Amém.', 'Constituição Pessoal', 'Escreva sua constituição de vida: prioridades, limites, rotinas, valores. Assine como documento oficial.', 4, 200),
('renovacao', 12, 'HÁBITOS SAUDÁVEIS', 'Instalar rotinas que sustentam mudança', 'Engenharia de Hábitos', 'Escolha 3 hábitos-chave: manhã, tarde, noite. Use técnica do empilhamento. Crie lembretes visuais.', 'Trio de Ouro', 'Execute perfeitamente seus 3 novos hábitos. Registre horário, duração, sensação. Não falhe nenhum.', 'Exercita-te na piedade - 1 Timóteo 4:7', 'Hábitos são tijolos da transformação. Cada repetição fortalece a nova identidade.', 'Senhor, da-me disciplina para criar hábitos santos. Que minha rotina Te glorifique. Amém.', 'Tracker de Hábitos', 'Crie planilha visual para rastrear hábitos. Use cores: verde (feito), amarelo (parcial), vermelho (perdido).', 3, 180),
('renovacao', 13, 'RELACIONAMENTOS REAIS', 'Reconectar com pessoas importantes', 'Mapeamento Relacional', 'Liste relacionamentos: Perdidos (reconectar), Fracos (fortalecer), Tóxicos (limitar), Novos (cultivar).', 'Conexão Analógica', 'Passe 4 horas em interações presenciais reais. Sem celular visível. Ouça mais que fale.', 'O homem não foi feito para estar só - Gênesis 2:18', 'Relacionamentos digitais são sombras. Relacionamentos reais são substância. Invista no que é real.', 'Senhor, restaura meus relacionamentos. Ensina-me a amar presencialmente. Amém.', 'Árvore Genealógica Social', 'Desenhe sua rede social: família, amigos próximos, colegas, conhecidos. Marque prioridades de investimento.', 3, 180);

-- Continue com dias 14-40 (versão resumida para completar rapidamente)
INSERT INTO track_daily_content (track_slug, day_number, title, objective, main_activity_title, main_activity_content, main_challenge_title, main_challenge_content, devotional_verse, devotional_reflection, devotional_prayer, bonus_activity_title, bonus_activity_content, difficulty_level, max_points) VALUES
('renovacao', 14, 'PROPÓSITO RENOVADO', 'Descobrir missão de vida pós-dependência', 'Busca do Propósito', 'Reflita: Para que Deus me libertou? Como posso servir? Que impacto quero causar? Escreva declaração de missão.', 'Dia de Serviço', 'Dedique 4 horas servindo outros gratuitamente. Experimente diferentes formas de ajudar.', 'Porque somos feitura sua, criados em Cristo Jesus para as boas obras - Efésios 2:10', 'Deus não o libertou apenas para seu bem-estar. Você foi liberto para libertar outros.', 'Senhor, revela meu propósito. Como posso usar minha liberdade para Te servir? Amém.', 'Mapa de Impacto', 'Desenhe como sua transformação pode impactar: família, trabalho, comunidade, reino de Deus.', 3, 200),
('renovacao', 15, 'MEIO CAMINHO', 'Celebrar 15 dias e renovar energia', 'Avaliação de Meio Termo', 'Analise mudanças: físicas, mentais, espirituais, relacionais. Compare fotos, depoimentos, métricas.', 'Celebração Significativa', 'Organize celebração com apoiadores. Compartilhe testemunho. Renove compromissos para segunda metade.', 'Fiel é o que vos chama, o qual também o fará - 1 Tessalonicenses 5:24', 'Meio caminho vencido! Deus que começou a obra vai completá-la. Confia no processo.', 'Senhor, obrigado por me trazer até aqui. Complete Tua obra em mim. Amém.', 'Cápsula do Tempo', 'Escreva carta para você do dia 40. Lacre, só abra na formatura.', 3, 250),
('renovacao', 16, 'CRIATIVIDADE LIBERTA', 'Despertar dons artísticos e criativos', 'Laboratório Criativo', 'Experimente: desenho, música, escrita, dança, artesanato. Descubra talentos adormecidos.', 'Dia de Arte', 'Crie algo belo com as mãos. Compartilhe com família. Registro fotográfico (não poste).', 'Todo dom perfeito vem do alto - Tiago 1:17', 'A dependência matou sua criatividade. Agora ela ressurge. Deus é criativo e você também.', 'Senhor, desperta minha criatividade. Que eu crie coisas que Te glorifiquem. Amém.', 'Galeria Pessoal', 'Crie espaço para expor suas criações. Convide família para "vernissage" caseiro.', 2, 180),
('renovacao', 17, 'EXERCÍCIO MENTAL', 'Fortalecer capacidade cognitiva', 'Ginástica Cerebral', 'Pratique: leitura profunda, quebra-cabeças, xadrez, memorização, matemática mental, novo idioma.', 'Desafio Intelectual', 'Leia 50 páginas, resolva 20 problemas, memorize 10 versículos, aprenda 20 palavras nova língua.', 'Transformai-vos pela renovação do vosso entendimento - Romanos 12:2', 'Sua mente foi dopada por estímulos vazios. Agora precisa de exercícios para se fortalecer.', 'Senhor, renova meu entendimento. Que minha mente Te glorifique. Amém.', 'Academia Mental', 'Crie rotina de exercícios mentais: puzzles matinais, leitura vespertina, memorização noturna.', 3, 180),
('renovacao', 18, 'SAÚDE FÍSICA', 'Reparar danos físicos da dependência', 'Check-up Completo', 'Avalie: postura, visão, sono, dores, peso, condicionamento. Crie plano de recuperação física.', 'Atleta Sagrado', 'Exercite-se 60 min, coma perfeitamente, durma 8h, hidrate-se, alongue-se, respire conscientemente.', 'Vosso corpo é templo do Espírito Santo - 1 Coríntios 6:19', 'Seu corpo é templo sagrado que foi profanado. Hora de restaurar e consagrar novamente.', 'Senhor, ajuda-me a cuidar do templo que me deste. Que ele Te honre. Amém.', 'Plano de Restauração', 'Crie cronograma de 30 dias para restaurar: postura, visão, sono, condicionamento físico.', 3, 180),
('renovacao', 19, 'GENEROSIDADE', 'Praticar doação e serviço', 'Coração Generoso', 'Pratique: doação financeira, doação de tempo, doação de talentos, doação de atenção.', 'Dia do Doador', 'Doe algo valioso sem esperar retorno. Sirva secretamente. Abençoe anonimamente.', 'Mais bem-aventurada coisa é dar do que receber - Atos 20:35', 'A dependência o tornou egocêntrico. A liberdade o torna generoso. Doe-se aos outros.', 'Senhor, cria em mim coração generoso. Que eu seja canal de Tuas bênçãos. Amém.', 'Lista de Doações', 'Faça lista mensal de doações: dinheiro, tempo, talentos, coisas. Seja generoso sistemático.', 2, 180),
('renovacao', 20, 'MEIO CAMINHO VENCIDO', 'Marcar metade da jornada', 'Grande Avaliação', 'Compare 20 dias: tempo tela, ansiedade, relacionamentos, projetos, saúde, espiritualidade.', 'Celebração de Meio Caminho', 'Organize evento com apoiadores. Testemunho, renovação de compromissos, preparação para segunda metade.', 'Tendo por certo que aquele que começou boa obra a aperfeiçoará - Filipenses 1:6', 'Metade da jornada vencida! Deus vai completar a transformação. Confia no processo.', 'Senhor, complete Tua obra em mim. Que os próximos 20 dias sejam de consolidação. Amém.', 'Medalha de Meio Caminho', 'Crie certificado especial: "20 DIAS VENCIDOS - Metade da jornada conquistada!"', 3, 300);

-- Dias 21-30: Fase FORTALECIMENTO
INSERT INTO track_daily_content (track_slug, day_number, title, objective, main_activity_title, main_activity_content, main_challenge_title, main_challenge_content, devotional_verse, devotional_reflection, devotional_prayer, bonus_activity_title, bonus_activity_content, difficulty_level, max_points) VALUES
('renovacao', 21, 'FORTALECIMENTO INTERIOR', 'Consolidar mudanças internas', 'Avaliação de Força', 'Teste sua resistência: exponha-se controladamente a tentações pequenas. Observe reações.', 'Dia de Tentação', 'Visite locais onde usava celular compulsivamente. Mantenha controle total. Prove sua força.', 'O que não me mata me fortalece', 'Você está mais forte. Pequenas tentações não o abalão mais. Teste sua nova força.', 'Senhor, mostra-me quão forte me tornei. Que eu confie na Tua força em mim. Amém.', 'Medidor de Força', 'Crie escala 1-10 para resistência. Teste-se semanalmente. Comemore crescimento.', 2, 200),
('renovacao', 22, 'LIDERANÇA EMERGENTE', 'Começar a liderar outros', 'Projeto de Mentoria', 'Identifique alguém começando jornada similar. Ofereça apoio baseado em sua experiência.', 'Mentor por Um Dia', 'Seja mentor/apoiador de alguém por 24h. Use sua experiência para encorajar outros.', 'Quem muito recebeu, muito será cobrado - Lucas 12:48', 'Você recebeu liberdade. Agora é responsável por ajudar outros a encontrá-la também.', 'Senhor, usa minha experiência para libertar outros. Que eu seja ponte de esperança. Amém.', 'Manual de Mentoria', 'Escreva guia com 10 lições aprendidas para passar adiante.', 2, 200),
('renovacao', 23, 'VISÃO DE FUTURO', 'Planejar vida pós-programa', 'Arquiteto do Futuro', 'Desenhe vida daqui 1 ano: rotinas, relacionamentos, projetos, conquistas, contribuições.', 'Viver o Futuro', 'Aja hoje como a pessoa que será em 1 ano. Tome decisões do futuro você.', 'Eu sei os planos que tenho para ti - Jeremias 29:11', 'Deus tem planos de bem para você. Sua liberdade é apenas o começo de algo maior.', 'Senhor, revela Teus planos para mim. Alinha meus sonhos aos Teus. Amém.', 'Mapa dos Sonhos', 'Crie quadro visual com seus sonhos para 1, 5, 10 anos. Cole no quarto.', 2, 180),
('renovacao', 24, 'GRATIDÃO PROFUNDA', 'Cultivar coração agradecido', 'Inventário de Gratidão', 'Liste 100 coisas pelas quais é grato. Inclua: pessoas, experiências, lições, transformações.', 'Dia de Agradecimento', 'Expresse gratidão concretamente: cartas, ligações, presentes, ações. Surpreenda pessoas.', 'Em tudo dai graças - 1 Tessalonicenses 5:18', 'Gratidão transforma perspectiva. O que antes era prisão agora é trampolim para voo.', 'Senhor, obrigado por tudo: dor que me despertou, pessoas que me apoiaram, força que me deste. Amém.', 'Jarra da Gratidão', 'Escreva daily uma gratidão em papel, coloque na jarra. Leia todas no dia 40.', 2, 180),
('renovacao', 25, 'RESISTÊNCIA TESTADA', 'Testar solidez da transformação', 'Teste de Estresse', 'Enfrente situação estressante propositalmente. Observe se mantém equilíbrio sem celular.', 'Crise Simulada', 'Simule crise que antes o levaria ao celular. Use ferramentas saudáveis de enfrentamento.', 'Provei-vos como ouro que se apura no fogo - 1 Pedro 1:7', 'Sua fé e transformação precisam ser testadas. O ouro puro resiste ao fogo.', 'Senhor, que eu passe em todos os testes. Que minha transformação seja genuína e duradoura. Amém.', 'Certificado de Resistência', 'Documente cada teste superado. "Provado e aprovado" em várias situações.', 3, 200),
('renovacao', 26, 'SABEDORIA ADQUIRIDA', 'Consolidar aprendizados', 'Livro da Sabedoria', 'Compile todas as lições aprendidas em 26 dias. Crie manual pessoal de sabedoria.', 'Conselheiro Sábio', 'Seja conselheiro para si mesmo. Que conselhos daria para quem está começando?', 'O princípio da sabedoria é o temor do Senhor - Provérbios 9:10', 'Você adquiriu sabedoria preciosa através da dor. Não desperdice essas lições.', 'Senhor, que eu seja sábio com as lições aprendidas. Que outros se beneficiem. Amém.', 'Biblioteca de Lições', 'Organize todas as anotações por temas: tentação, resistência, relacionamentos, propósito.', 2, 180),
('renovacao', 27, 'COMUNIDADE SÓLIDA', 'Fortalecer rede de apoio', 'Auditoria Social', 'Avalie sua rede: quem realmente apoia, quem prejudica, quem é neutro. Ajuste relacionamentos.', 'Dia da Comunidade', 'Invista intensivamente em relacionamentos construtivos. Limite tempo com influências negativas.', 'Como ferro afia ferro, assim homem afia homem - Provérbios 27:17', 'Você precisa de pessoas que o desafiem para o bem. Cerque-se de ferro afiado.', 'Senhor, cerca-me de pessoas que me aproximem de Ti. Remove influências prejudiciais. Amém.', 'Círculos Sociais', 'Desenhe seus círculos: íntimo (5), próximo (15), social (50). Invista adequadamente.', 2, 180),
('renovacao', 28, 'EXCELÊNCIA HABITUAL', 'Viver em alto padrão', 'Padrão de Excelência', 'Defina padrões altos para: trabalho, relacionamentos, saúde, espiritualidade. Viva-os hoje.', 'Dia de Elite', 'Aja como pessoa de elite em todas as áreas. Alto padrão em tudo que fizer.', 'Sede perfeitos como perfeito é vosso Pai - Mateus 5:48', 'Deus o chama para excelência. Não se contente com mediocridade em nenhuma área.', 'Senhor, ajuda-me a viver em excelência. Que tudo que eu fizer Te honre. Amém.', 'Manual de Excelência', 'Escreva padrões pessoais para cada área da vida. Cole onde possa ver daily.', 2, 200),
('renovacao', 29, 'PREPARAÇÃO FINAL', 'Preparar para últimos dias', 'Reta Final', 'Analise o que falta para completar transformação. Intensifique esforços nas áreas fracas.', 'Sprint Final', 'Dê o máximo em todas as áreas. Últimos dias devem ser os melhores.', 'Aquele que perseverar até o fim será salvo - Mateus 24:13', 'Faltam poucos dias. Não relaxe agora. A reta final define campeões.', 'Senhor, da-me força para terminar bem. Que os últimos dias sejam os mais fortes. Amém.', 'Cronômetro de Vitória', 'Conte regressivo para dia 40. Cada dia é conquista mais próxima.', 2, 200),
('renovacao', 30, 'NOVA NORMALIDADE', 'Estabelecer rotina sustentável', 'Consolidação Total', 'Documente sua nova normalidade: rotinas automáticas, pensamentos padrão, reações naturais.', 'Vida Normal', 'Viva dia absolutamente normal da nova versão. Sem esforço consciente, apenas sendo.', 'Fez novas todas as coisas - Apocalipse 21:5', 'Você estabeleceu nova normalidade. Não é mais esforço, é quem você é agora.', 'Senhor, obrigado pela nova normalidade. Que ela se mantenha e se aprofunde. Amém.', 'Manual da Nova Normalidade', 'Documente como é sua vida normal agora vs antes. Celebre a transformação.', 1, 300);

-- Dias 31-40: Fase MANUTENÇÃO
INSERT INTO track_daily_content (track_slug, day_number, title, objective, main_activity_title, main_activity_content, main_challenge_title, main_challenge_content, devotional_verse, devotional_reflection, devotional_prayer, bonus_activity_title, bonus_activity_content, difficulty_level, max_points) VALUES
('renovacao', 31, 'MANUTENÇÃO PREVENTIVA', 'Criar sistemas de sustentação', 'Plano de Manutenção', 'Crie sistemas para manter transformação: check-ins semanais, mentoria contínua, limites permanentes.', 'Sistema Blindado', 'Teste todos os sistemas de proteção. Identifique falhas, corrija imediatamente.', 'Vigia e ora para não entrares em tentação - Mateus 26:41', 'Vigilância eterna é preço da liberdade. Crie sistemas que funcionem no piloto automático.', 'Senhor, ajuda-me a ser vigilante sempre. Que eu não relaxe na guarda. Amém.', 'Protocolo de Emergência', 'Crie protocolo detalhado para usar em caso de recaída ou tentação forte.', 2, 200),
('renovacao', 32, 'MULTIPLICAÇÃO', 'Reproduzir transformação em outros', 'Estratégia de Multiplicação', 'Planeje como vai ajudar outros: grupos de apoio, testemunhos, mentoria, conteúdo.', 'Primeiro Discípulo', 'Comece oficialmente a mentorear alguém. Use sua experiência para acelerar jornada dele.', 'Ide e fazei discípulos - Mateus 28:19', 'Você foi transformado para transformar outros. Sua liberdade deve se multiplicar.', 'Senhor, usa-me para libertar muitos outros. Que minha história seja esperança. Amém.', 'Plano de Discipulado', 'Crie currículo de 10 lições baseado em sua jornada para ensinar outros.', 2, 200),
('renovacao', 33, 'LEGADO CONSTRUÍDO', 'Definir impacto duradouro', 'Arquitetura de Legado', 'Defina que legado quer deixar: na família, trabalho, comunidade, reino de Deus.', 'Dia de Legado', 'Aja pensando no legado. Cada decisão: "Isso constrói o legado que quero?"', 'Boa árvore produz bons frutos - Mateus 7:17', 'Você é árvore transformada. Agora deve produzir frutos que alimentem gerações.', 'Senhor, que minha vida produza frutos duradouros. Que meu legado Te glorifique. Amém.', 'Árvore de Legado', 'Desenhe árvore com frutos que quer produzir: filhos transformados, pessoas libertas, obras duradouras.', 2, 200),
('renovacao', 34, 'AUTORIDADE ESPIRITUAL', 'Exercer domínio sobre tentações', 'Teste de Autoridade', 'Enfrente tentação com autoridade espiritual. Declare: "Eu tenho poder sobre isso!"', 'Comandante Espiritual', 'Aja como quem tem autoridade sobre mundo digital. Você manda, não ele.', 'Deu-lhes poder sobre espíritos imundos - Mateus 10:1', 'Você recebeu autoridade espiritual através da vitória. Use esse poder para vencer sempre.', 'Senhor, obrigado pela autoridade que me deste. Que eu a use para Tua glória. Amém.', 'Certificado de Autoridade', 'Escreva decreto: "Eu tenho autoridade sobre toda tentação digital em nome de Jesus!"', 2, 200),
('renovacao', 35, 'MESTRE DA DISCIPLINA', 'Dominar autocontrole total', 'Academia de Disciplina', 'Teste disciplina em áreas difíceis: dieta, exercício, sono, trabalho, relacionamentos.', 'Disciplina Olímpica', 'Mantenha padrão olímpico de disciplina em todas as áreas por 24h completas.', 'Todo atleta se abstém de tudo - 1 Coríntios 9:25', 'Você é atleta espiritual de elite. Sua disciplina deve inspirar outros.', 'Senhor, que minha disciplina seja testemunho do Teu poder transformador. Amém.', 'Manual de Disciplina', 'Documente todas as disciplinas que adquiriu. Crie guia para outros seguirem.', 2, 200),
('renovacao', 36, 'SABEDORIA MADURA', 'Demonstrar maturidade adquirida', 'Conselho de Sábios', 'Reúna pessoas para ouvi-lo sobre lições de vida. Compartilhe sabedoria adquirida.', 'Sábio Conselheiro', 'Seja procurado para conselhos. Demonstre sabedoria em palavras e ações.', 'Pelos frutos os conhecereis - Mateus 7:20', 'Sua sabedoria deve ser evidente nos frutos. Pessoas devem procurar seus conselhos.', 'Senhor, que a sabedoria que me deste beneficie muitos. Que eu seja sábio sempre. Amém.', 'Biblioteca de Sabedoria', 'Compile todos os insights em livro pessoal de sabedoria para deixar de legado.', 1, 200),
('renovacao', 37, 'GRATIDÃO TRANSBORDANTE', 'Expressar gratidão profunda', 'Festival de Gratidão', 'Organize dia inteiro de gratidão: cartas, ligações, presentes, ações para todos que ajudaram.', 'Embaixador da Gratidão', 'Seja exemplo de gratidão. Que outros aprendam a ser gratos vendo você.', 'Dai graças em tudo - 1 Tessalonicenses 5:18', 'Gratidão é marca dos transformados. Seja conhecido como pessoa profundamente grata.', 'Senhor, obrigado por tudo: a dor que me acordou, as pessoas que me ajudaram, a transformação que me deste. Amém.', 'Museu da Gratidão', 'Crie exposição com fotos, cartas, objetos que representam jornada de gratidão.', 1, 200),
('renovacao', 38, 'PAZ CONQUISTADA', 'Viver em paz profunda', 'Inventário de Paz', 'Documente a paz conquistada: mental, emocional, espiritual, relacional, financeira.', 'Embaixador da Paz', 'Seja agente de paz em todos os ambientes. Leve tranquilidade onde chegar.', 'Deixo-vos a paz, a minha paz vos dou - João 14:27', 'Você conquistou a paz de Cristo. Essa paz deve se irradiar para outros.', 'Senhor, obrigado pela paz que supera entendimento. Que eu seja canal dessa paz. Amém.', 'Jardim da Paz', 'Crie espaço físico dedicado à paz: plantas, música suave, versículos, ambiente sereno.', 1, 200),
('renovacao', 39, 'VÉSPERA DA VITÓRIA', 'Preparar celebração final', 'Preparativos de Vitória', 'Organize celebração do dia 40: convidados, programa, testemunho, compromissos futuros.', 'Ensaio Geral', 'Pratique seu testemunho de 40 dias. Prepare-se para inspirar outros com sua história.', 'Combati o bom combate, terminei a carreira - 2 Timóteo 4:7', 'Véspera da vitória total. Você combateu, perseverou, venceu. Amanhã é coroação.', 'Senhor, obrigado por me trazer até aqui. Amanhã celebro Tua fidelidade e poder. Amém.', 'Convite de Formatura', 'Crie convites especiais para celebração: "40 Dias de Transformação - Renascimento Completo"', 1, 250),
('renovacao', 40, 'RENASCIMENTO COMPLETO', 'Celebrar transformação total', 'Cerimônia de Formatura', 'Celebração oficial: retrospectiva, testemunho, certificado, compromissos futuros, ação de graças.', 'Legado Vivo', 'Comprometa-se com mentoria ativa, manutenção vigilante, crescimento contínuo, família primeiro, propósito claro.', 'Combati o bom combate, acabei a carreira, guardei a fé - 2 Timóteo 4:7', '40 dias no deserto digital. Como Jesus, você foi testado e venceu. Você renasceu completamente.', 'Senhor, Tu me trouxeste da morte digital para vida plena. Dedico esta nova vida a Ti. Use-me para libertar outros. Amém.', 'Certificado de Libertação', 'Certificado oficial: "40 DIAS DE RENOVAÇÃO TOTAL - Venceu dependência severa, renasceu em Cristo, transformou-se completamente"', 1, 500);