// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovphnpiwioscxfryjcdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92cGhucGl3aW9zY3hmcnlqY2RmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNDQ2NjAsImV4cCI6MjA3MDYyMDY2MH0.sO8KlCCDUPYBkdAH-Mw00qCphN63Qp_8DclLoWO7nSw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});